config/routes.rb
Lomlist3::Application.routes.draw do
  devise_for :users, :skip => :registrations, :controllers => { :invitations => 'users/invitations' }

  match '/items/new_next' => 'items#new_next', :via => :post
  match '/items/new' => 'items#new', :via => :get
  match '/items/printview' => 'items#printview', :via => :get
  match '/items/search' => 'items#search'
  match '/items/delete_by_number' => 'items#destroy'
  match '/items/edit_by_number' => 'items#edit'
  match '/items' => 'items#index', :via => :get
  match '/items' => 'items#create', :via => :post
  match '/items/:number' => 'items#show', :via => :get
  match '/items/:number' => 'items#update', :via => :put
  match '/items/:number' => 'items#destroy', :via => :delete
  match '/items/:number/edit' => 'items#edit', :via => :get

  match 'tags/:tagname/items' => 'items#index', :tagname =>  /[^\/]+/
  
  match '/help' => 'pages#display'

  resources :tags do
    collection do
      get 'tag_report'
    end
  end

  resources :act_types

  match 'acttype/:typename' => 'items#search_by_act_type'
  
  match '/feedback_messages' => 'feedback_messages#send_message', :via => :post
  
  root :to => 'items#index'   

end

app/views/shared/_menu.html.erb
<% if user_signed_in? %>
  <%= link_to "List all", items_path %>	  

  <%= link_to "Tag Report", '/tags/tag_report' %>

  <%= link_to "Maintain Act Types", act_types_path %>

  <span id="hello_user">
    Hello, <%= current_user.first_name %>
  </span>  
  <% if current_user.invitation_limit > 0 %>
    <%= link_to "Send an Invitation (#{current_user.invitation_limit} left)", new_user_invitation_path %>
  <% end %>  

  <%= link_to "Print-friendly", '/items/printview' %>
  
  <%= link_to "FAQ", '/help'%>
  
<% end %>