config/routes.rb
Lomlist3::Application.routes.draw do
  devise_for :users, :skip => :registrations, :controllers => { :invitations => 'users/invitations' }

  match '/items/new_next' => 'items#new_next', :via => :post
  match '/items/new' => 'items#new', :via => :get
  match '/items/printview' => 'items#printview', :via => :get
  match '/items/search' => 'items#search'
  match '/items/delete_by_number' => 'items#destroy'
  match '/items/edit_by_number' => 'items#edit'
  match '/items' => 'items#index', :via => :get
  match '/items' => 'items#create', :via => :post
  match '/items/:number' => 'items#show', :via => :get
  match '/items/:number' => 'items#update', :via => :put
  match '/items/:number' => 'items#destroy', :via => :delete
  match '/items/:number/edit' => 'items#edit', :via => :get

  match 'tags/:tagname/items' => 'items#index', :tagname =>  /[^\/]+/
  
  match '/help' => 'pages#display'

  resources :tags do
    collection do
      get 'tag_report'
    end
  end

  resources :act_types

  match 'acttype/:typename' => 'items#search_by_act_type'
  
  match '/feedback_messages' => 'feedback_messages#send_message', :via => :post
  
  root :to => 'items#index'   

end

app/models/tag.rb
# A Tag is a label used to categorize an item.
# An item may have many tags.
class Tag < ActiveRecord::Base
  attr_accessible :name, :user
  has_many :taggings
  has_many :items, :through => :taggings
  belongs_to :user
  
  # input is a delimited list of tags 
  # output is an array of tags 
  def self.parse(list)
    tag_names = []
    # first, pull out the quoted tags
    list.gsub!(/\"(.*?)\"\s*/ ) { tag_names << $1; "" } 
    # then, replace all commas with a space
    list.gsub!(/,/, " ")
    # then, get whatever's left
    tag_names.concat list.split(/\s/)
    # strip whitespace from the names
    tag_names = tag_names.map { |t| t.strip }
    # delete any blank tag names
    tag_names = tag_names.delete_if { |t| t.empty? }    
    return tag_names
  end  
  
  def self.used_tags(user)
    Tag.joins(:taggings).select("distinct tags.id, tags.name, LOWER(tags.name)").where("tags.user_id = ?", user.id).order("LOWER(tags.name)") 
  end
  
  def self.unused_tags(user)
    find_by_sql(["SELECT id, name FROM tags WHERE user_id = ? AND id NOT IN (SELECT tag_id FROM taggings) ORDER BY LOWER(name)", user.id])
  end

  def add_item_manually(item, user)
    Tagging.create(:tag => self, :item => item, :user => user)
  end
  
  def items_count
    self.taggings.count
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
   before_filter :authenticate_user!
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to '/tags/tag_report' }
      format.json { head :no_content }
    end
  end

  def tag_report
    @used_tags = Tag.used_tags(current_user)
    @unused_tags = Tag.unused_tags(current_user)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/tags/tag_report.html.erb
<h2>Total Number of Items: <%= Item.where(:user_id => current_user.id).count %> </h2>
<h1>Tags</h1>
<h2>Used Tags</h2>
<% @used_tags.each do |tag|  %>
	<%= link_to tag.name, "/tags/#{tag.name}/items" %>
  <%= tag.items_count %>
  <br/>
<% end %>

<h2>Unused Tags</h2>
<% @unused_tags.each do |tag| %>
  <%= tag.name %>
  <%= link_to 'Delete', tag, :method => :delete,  :confirm => 'Are you sure?' %></td> 
 <br/>
<% end %>