config/routes.rb
Lomlist3::Application.routes.draw do
  devise_for :users, :skip => :registrations, :controllers => { :invitations => 'users/invitations' }

  match '/items/new_next' => 'items#new_next', :via => :post
  match '/items/new' => 'items#new', :via => :get
  match '/items/printview' => 'items#printview', :via => :get
  match '/items/search' => 'items#search'
  match '/items/delete_by_number' => 'items#destroy'
  match '/items/edit_by_number' => 'items#edit'
  match '/items' => 'items#index', :via => :get
  match '/items' => 'items#create', :via => :post
  match '/items/:number' => 'items#show', :via => :get
  match '/items/:number' => 'items#update', :via => :put
  match '/items/:number' => 'items#destroy', :via => :delete
  match '/items/:number/edit' => 'items#edit', :via => :get

  match 'tags/:tagname/items' => 'items#index', :tagname =>  /[^\/]+/
  
  match '/help' => 'pages#display'

  resources :tags do
    collection do
      get 'tag_report'
    end
  end

  resources :act_types

  match 'acttype/:typename' => 'items#search_by_act_type'
  
  match '/feedback_messages' => 'feedback_messages#send_message', :via => :post
  
  root :to => 'items#index'   

end

app/controllers/act_types_controller.rb
class ActTypesController < ApplicationController
   before_filter :authenticate_user!
  # GET /act_types
  # GET /act_types.json
  def index
    @act_types = current_user.act_types.order("name")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @act_types }
    end
  end

  # GET /act_types/1
  # GET /act_types/1.json
  def show
    @act_type = ActType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @act_type }
    end
  end

  # GET /act_types/new
  # GET /act_types/new.json
  def new
    @act_type = ActType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @act_type }
    end
  end

  # GET /act_types/1/edit
  def edit
    @act_type = ActType.find(params[:id])
  end

  # POST /act_types
  # POST /act_types.json
  def create
    @act_type = ActType.new(params[:act_type])
    @act_type.user = current_user

    respond_to do |format|
      if @act_type.save
        format.html { redirect_to @act_type, notice: 'Act type was successfully created.' }
        format.json { render json: @act_type, status: :created, location: @act_type }
      else
        format.html { render action: "new" }
        format.json { render json: @act_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /act_types/1
  # PUT /act_types/1.json
  def update
    @act_type = ActType.find(params[:id])

    respond_to do |format|
      if @act_type.update_attributes(params[:act_type])
        format.html { redirect_to @act_type, notice: 'Act type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @act_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /act_types/1
  # DELETE /act_types/1.json
  def destroy
    @act_type = ActType.find(params[:id])
    @act_type.destroy

    respond_to do |format|
      format.html { redirect_to act_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/act_types_helper.rb
module ActTypesHelper
end

app/views/act_types/_form.html.erb
<%= form_for(@act_type) do |f| %>
  <% if @act_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act_type.errors.count, "error") %> prohibited this act_type from being saved:</h2>

      <ul>
      <% @act_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/act_types/edit.html.erb
<h1>Editing act_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @act_type %> |
<%= link_to 'Back', act_types_path %>

app/views/act_types/index.html.erb
<h1>Listing act_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @act_types.each do |act_type| %>
  <% item_count = current_user.items.where(:act_type => act_type.name).count %>
  <tr>
    <td><%= act_type.name %></td>    
    <td><%= link_to 'Edit', edit_act_type_path(act_type) %></td>
    <td>
    <% unless item_count > 0 %>
      <%= link_to 'Delete', act_type, confirm: 'Are you sure?', method: :delete %>
    <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Act type', new_act_type_path %>

app/views/act_types/new.html.erb
<h1>New act_type</h1>

<%= render 'form' %>

<%= link_to 'Back', act_types_path %>

app/views/act_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @act_type.name %>
</p>


<%= link_to 'Edit', edit_act_type_path(@act_type) %> |
<%= link_to 'Back', act_types_path %>