config/routes.rb
Lomlist3::Application.routes.draw do
  devise_for :users, :skip => :registrations, :controllers => { :invitations => 'users/invitations' }

  match '/items/new_next' => 'items#new_next', :via => :post
  match '/items/new' => 'items#new', :via => :get
  match '/items/printview' => 'items#printview', :via => :get
  match '/items/search' => 'items#search'
  match '/items/delete_by_number' => 'items#destroy'
  match '/items/edit_by_number' => 'items#edit'
  match '/items' => 'items#index', :via => :get
  match '/items' => 'items#create', :via => :post
  match '/items/:number' => 'items#show', :via => :get
  match '/items/:number' => 'items#update', :via => :put
  match '/items/:number' => 'items#destroy', :via => :delete
  match '/items/:number/edit' => 'items#edit', :via => :get

  match 'tags/:tagname/items' => 'items#index', :tagname =>  /[^\/]+/
  
  match '/help' => 'pages#display'

  resources :tags do
    collection do
      get 'tag_report'
    end
  end

  resources :act_types

  match 'acttype/:typename' => 'items#search_by_act_type'
  
  match '/feedback_messages' => 'feedback_messages#send_message', :via => :post
  
  root :to => 'items#index'   

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  # Set up accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :invitation_limit
  has_many :act_types 
  has_many :items
  has_many :taggings
  has_many :tags 
  after_invitation_accepted :set_up_new_user
  belongs_to :invited_by, :class_name => "User"
  # attr_accessible :title, :body
  
  INITIAL_ACT_TYPES = [
    ActType.new(:name => "MA"),  # "My agenda"
    ActType.new(:name => "SEC"), # "Secondary items on my agenda"
    ActType.new(:name => "MAINT"), # "Maintenance"
    ActType.new(:name => "FO"), # "For others"
    ActType.new(:name => "BUDG")  # "Budgeting and finances"
   ]
   
   SAMPLE_ITEM = Item.new(:create_date => Time.now, :number => 1, 
   :act_type => "MA",
   :item_desc => "Your sample item. Do an <b>important</b> thing. It might need a link to <a href=\"http://www.example.com\">www.example.com</a>.\n\n<br/><br/>Line breaks are nice! It might have <u>underline</u> or <i>italics</i>! Edit this item or delete it.")

  # New item date is the latest date of an item 
  def new_item_date
    newest_item = Item.where(:user_id => self.id).order("create_date DESC").first
    if newest_item
      newest_item.create_date
    else
      Time.new
    end
  end
  
  def set_up_new_user 
    # Give them an initial set of act types 
    self.act_types=User::INITIAL_ACT_TYPES
    
    # Start them with a sample to-do item
    self.items << User::SAMPLE_ITEM
    
    # Ask for their first and last name
    
    # Show them the intro/faq/readme

  end

end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  
  def create 
    super 
    self.resource.invitation_limit = self.resource.class.invitation_limit
    self.resource.save
  end
  
end

app/views/users/invitations/edit.html.erb
<h2>Welcome to mydothis.com!</h2>
<h2>Please set your password</h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>
  
  <p><%= f.label :first_name %><br />
  <%= f.text_field :first_name %></p>
  
  <p><%= f.label :last_name %><br />
  <%= f.text_field :last_name %></p>
  
  <p><%= f.submit "Set my password" %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2>Send invitation</h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <p><%= f.label field %>*<br />
    <%= f.text_field field %></p>
  <% end -%>
  
  Name of person you are inviting (optional)<br/>
<p>first name <br/ >
<%= text_field "user", "first_name" %></p>
    
<p>last name <br/ >
<%= text_field "user", "last_name" %></p>
    
  <p><%= f.submit "Send an invitation" %></p>
<% end %>

<%= link_to "Home", after_sign_in_path_for(resource_name) %><br />